### ISSUE TITLE
RSS/Atom feed

### ISSUE THREAD

**Issue by fhuitelec** [SelrahcD/selrahcd.github.io#6]
Hey there,

Could you add an **Atom/RSS feed**? I like to reed your blog from time to time and I'd like to see your updates in my RSS aggregator (more convenient, toussa, toussa)

Suggestion: [Jekyll-feed](https://github.com/jekyll/jekyll-feed)

Thanks! ❤️

**Comment by SelrahcD** [comment]
Je viens de voir l'issue.

Il fait pas le taff http://blog.chorip.am/feed.xml ?

**Comment by fhuitelec** [comment]
Impec' 👍  Y'a pas lien sur ta home, et j'avais juste essayé `/feed`
