### ISSUE TITLE
RSS feed seems to have disappeared

### ISSUE THREAD

**Issue by jdecool** [SelrahcD/selrahcd.github.io#9]
The RSS feed has been deleted in the 0195c9c00dc6716a8e34fe5197ffdf93d16fde5f commit.

Is it possible to add a new one ?

**Comment by SelrahcD** [comment]
Salut,
j'avais absolument pas vu cette issue... Heureusement que j'ai joué avec les boards de projet.

Je crois que c'est bon désormais, je l'avais corrigé à un moment. Le feed est dispo ici http://blog.chorip.am/feed.xml

**Comment by jdecool** [comment]
Tout semble OK !
👍 

Merci.
